# Site settings
title: Dicko Sow
email: s12.dsow@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A little about me and my dive into programming!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://s12dsow.github.io" # the base hostname & protocol for your site
twitter_username: s12dsow
github_username:  s12dsow

# Build settings
markdown: kramdown